### ISSUE TITLE
Second scene Bug

### ISSUE THREAD

**Issue by Rockbard** [AIGODLIKE/hdr_rotation#1]
Hey, thanks for the great add-on. 

If you create a second scene and will try to use the add-on It will raise an exception:

Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\blender_org\hdr_rotation\ops.py", line 47, in __init__
    self.nodes = get_node(node_tree=bpy.context.scene.world.node_tree)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'node_tree'

Attaching the project file. It's in the zip since Github do not allow to attach blend files for some reason.

[HDR rotation second scene bug.zip](https://github.com/user-attachments/files/15776319/HDR.rotation.second.scene.bug.zip)

**Comment by xmx-emm** [comment]
[1.0.3 ](https://github.com/AIGODLIKE/hdr_rotation/releases/tag/v1.0.3) released
