### ISSUE TITLE
Suggestion: Use click and drag instead of click

### ISSUE THREAD

**Issue by Rockbard** [AIGODLIKE/hdr_rotation#2]
If you leave it at default it could interfere with Shift + Right click to select several objects with the default right-click select keyboard scheme.

![image](https://github.com/AIGODLIKE/hdr_rotation/assets/39404436/e71313f0-c403-4a19-adc3-c7853777f7c8)

If we will change it to the "click and drag" option everything will work as intended.

**Comment by xmx-emm** [comment]
A better way is used, if the mouse is over the model, it is passed through the
Will be pushed in the next release
